---
title: "ESM242 - Optimization"
author: "Hunter Smith"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Setup

rm(list = ls())
setwd("/Users/hunte/Desktop/ESM 242")
library(tidyverse)
library(nloptr)
library(knitr)
```

```{r}
# Baseline Objective Function -- No Carbon Benefit

objective_baseline <- function(choice, a, b, c, p, delta)
{
  Q = exp(a - b / choice)
  benefits = p * Q * exp(-delta * choice) - c
  
  return(-benefits)
}

options=list("algorithm"="NLOPT_LN_COBYLA",xtol_rel=1e-8,maxeval=16000)

output_baseline = nloptr(x0 = 10,
                         eval_f = objective_baseline,
                         lb = 0,
                         opts = options,
                         a = 11.9466,
                         b = 104.9291,
                         c = 335,
                         p = 683.50,
                         delta = 0.05)
print(output_baseline$solution)
```

```{r}
# Objective Function Including Carbon Benefit

objective_carbon <- function(choice, a1, b1, a2, b2, c, p, rho, alpha, scc)
{
  Q = exp(a1 - b1 / choice)
  C = exp(a2 - b2 / choice)

  benefits = rho^choice * p * Q + 7403.06 - rho^choice * scc * alpha * C - c
  
  return(-benefits)
}

options=list("algorithm"="NLOPT_LN_COBYLA",xtol_rel=1e-8,maxeval=16000)

output_carbon = nloptr(x0 = 10,
                       eval_f = objective_carbon,
                       lb = 0,
                       opts = options,
                       a1 = 11.9466,
                       b1 = 104.9291,
                       a2 = 4.729,
                       b2 = 14.559,
                       c = 335,
                       p = 683.50,
                       rho = 1/1.05,
                       alpha = 0.21330949,
                       scc = 190)
print(output_carbon$solution)
```

```{r}
exp(4.729 - (14.559 / 45.81028))
exp(4.729 - (14.559 / 46.38087))
```

